"""compose-commit.py 单元测试。

覆盖 code-committer.md §5 固化：批次/累计统计、提交信息模板渲染、
空 done 类跳过、git baseline 查询、标题/body 80 字符截断。
"""
import json

import pytest


def _status(classes, batch_classes=None, **extra):
    """构造 status JSON。classes=[(name, status, total, tested)]。"""
    data = {
        "classes_status": [
            {"name": n, "status": s, "methods_total": t, "methods_tested": td}
            for n, s, t, td in classes
        ],
        "batch_classes": batch_classes or [c[0] for c in classes],
        "batch": 1,
        "baseline_commit": "abc123def",
        "branch_name": "main",
        "project_name": "myproject",
        "test_dir": "autotests",
    }
    data.update(extra)
    return data


# ── 统计计算 ──────────────────────────────────────────────────────────

class TestStats:
    def test_batch_and_cumulative(self, compose_commit):
        d = _status([
            ("Calculator", "done", 9, 9),
            ("FileView", "done", 10, 8),
            ("Failed", "failed", 5, 2),
        ], batch_classes=["Calculator", "FileView", "Failed"])
        # batch_classes 含全部 3 个；done 2 个
        s = compose_commit.compute_stats(d)
        assert s["batch_done_count"] == 2
        assert s["batch_total"] == 3
        assert s["batch_methods"] == 19  # 9+10
        assert s["batch_tested"] == 17   # 9+8
        assert s["cumulative_classes"] == 2
        assert s["cumulative_total"] == 3
        assert "Calculator" in s["batch_classes_str"]
        assert "FileView" in s["batch_classes_str"]

    def test_batch_subset_of_all(self, compose_commit):
        # 本批次只含部分类；累计统计所有 done
        d = _status([
            ("A", "done", 3, 3),
            ("B", "done", 4, 4),
            ("C", "done", 5, 5),
        ], batch_classes=["A"])  # 本批次只 A
        s = compose_commit.compute_stats(d)
        assert s["batch_done_count"] == 1
        assert s["cumulative_classes"] == 3  # 全部 done

    def test_empty_status(self, compose_commit):
        s = compose_commit.compute_stats({"classes_status": [], "batch_classes": []})
        assert s["batch_done_count"] == 0
        assert s["cumulative_classes"] == 0


# ── 信息渲染 ──────────────────────────────────────────────────────────

class TestComposeMessage:
    def test_basic_format(self, compose_commit):
        d = _status([("Calculator", "done", 9, 9)])
        s = compose_commit.compute_stats(d)
        msg = compose_commit.compose_message(d, s, git_dir=None)
        assert msg.startswith("test: add autotests for myproject batch 1")
        assert "Generated by qt-autotest-generator skill." in msg
        assert "Log: 新增 myproject 单元测试" in msg
        assert "Influence: 新增 1 个类的单元测试" in msg
        assert "Baseline: main @ abc123de" in msg

    def test_title_80_chars(self, compose_commit):
        d = _status([("Calculator", "done", 9, 9)],
                     project_name="a-very-long-project-name-that-exceeds-limit")
        s = compose_commit.compute_stats(d)
        msg = compose_commit.compose_message(d, s, git_dir=None)
        title = msg.split("\n")[0]
        assert len(title) <= 80

    def test_pms_issue_lines(self, compose_commit):
        d = _status([("A", "done", 1, 1)], pms_no="12345", issue_no="GH-678")
        s = compose_commit.compute_stats(d)
        msg = compose_commit.compose_message(d, s, git_dir=None)
        assert "PMS: 12345" in msg
        assert "Issue: GH-678" in msg

    def test_no_pms_issue_omitted(self, compose_commit):
        d = _status([("A", "done", 1, 1)])
        s = compose_commit.compute_stats(d)
        msg = compose_commit.compose_message(d, s, git_dir=None)
        assert "PMS:" not in msg
        assert "Issue:" not in msg

    def test_baseline_without_sha(self, compose_commit):
        d = _status([("A", "done", 1, 1)], baseline_commit="")
        s = compose_commit.compute_stats(d)
        msg = compose_commit.compose_message(d, s, git_dir=None)
        assert "unknown" in msg

    def test_git_dir_queries_git(self, compose_commit, tmp_path):
        # 建一个临时 git 仓库做 baseline 查询
        import subprocess
        repo = tmp_path / "repo"
        repo.mkdir()
        subprocess.check_call(["git", "init", "-q"], cwd=repo)
        subprocess.check_call(["git", "config", "user.email", "t@t.com"], cwd=repo)
        subprocess.check_call(["git", "config", "user.name", "t"], cwd=repo)
        (repo / "f.txt").write_text("x")
        subprocess.check_call(["git", "add", "."], cwd=repo)
        subprocess.check_call(["git", "commit", "-q", "-m", "init commit"], cwd=repo)
        sha = subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=repo).decode().strip()
        d = _status([("A", "done", 1, 1)], baseline_commit=sha)
        s = compose_commit.compute_stats(d)
        msg = compose_commit.compose_message(d, s, git_dir=str(repo))
        assert "init commit" in msg
        assert sha[:8] in msg

    def test_project_path_derivation(self, compose_commit):
        # 不传 project_name，传 project_path → 取 basename（对齐 code-committer §5）
        d = _status([("A", "done", 1, 1)])
        d.pop("project_name")
        d["project_path"] = "/home/user/repos/deepin-image-viewer"
        s = compose_commit.compute_stats(d)
        msg = compose_commit.compose_message(d, s, git_dir=None)
        assert "deepin-image-viewer" in msg
        assert "/home/user" not in msg

    def test_project_name_overrides_path(self, compose_commit):
        d = _status([("A", "done", 1, 1)],
                     project_name="custom-name",
                     project_path="/x/y/z")
        s = compose_commit.compute_stats(d)
        msg = compose_commit.compose_message(d, s, git_dir=None)
        assert "custom-name" in msg

    def test_baseline_no_git_dir_uses_placeholder(self, compose_commit):
        # 有 sha 但无 --git-dir → title 用占位，不暴露完整 sha
        d = _status([("A", "done", 1, 1)], baseline_commit="a1b2c3d4e5f6g7")
        s = compose_commit.compute_stats(d)
        msg = compose_commit.compose_message(d, s, git_dir=None)
        assert "a1b2c3d4" in msg  # 短 sha 仍在
        assert "a1b2c3d4e5f6g7" not in msg  # 完整 sha 不出现
        assert "--git-dir" in msg  # 提示

    def test_git_log_failed_uses_placeholder(self, compose_commit, tmp_path):
        # --git-dir 提供但 sha 不存在 → git log 失败 → title 用占位
        import subprocess
        repo = tmp_path / "repo"
        repo.mkdir()
        subprocess.check_call(["git", "init", "-q"], cwd=repo)
        d = _status([("A", "done", 1, 1)], baseline_commit="deadbeef0000")
        s = compose_commit.compute_stats(d)
        msg = compose_commit.compose_message(d, s, git_dir=str(repo))
        assert "deadbeef" in msg  # 短 sha 仍在
        assert "git log failed" in msg  # 占位提示


# ── CLI ───────────────────────────────────────────────────────────────

class TestCli:
    def test_outputs_message_exit_zero(self, compose_commit, tmp_path, capsys):
        sf = tmp_path / "status.json"
        sf.write_text(json.dumps(_status([("A", "done", 1, 1)])), encoding="utf-8")
        rc = compose_commit.commit_main_no_exit(["--status-file", str(sf)])
        out = capsys.readouterr().out
        assert rc == 0
        assert out.startswith("test: add")

    def test_no_done_classes_exit_two(self, compose_commit, tmp_path, capsys):
        sf = tmp_path / "status.json"
        sf.write_text(json.dumps(_status([("A", "failed", 1, 0)])), encoding="utf-8")
        rc = compose_commit.commit_main_no_exit(["--status-file", str(sf)])
        assert rc == 2
        assert "no done classes" in capsys.readouterr().out

    def test_write_to_file(self, compose_commit, tmp_path):
        sf = tmp_path / "status.json"
        sf.write_text(json.dumps(_status([("A", "done", 1, 1)])), encoding="utf-8")
        out = tmp_path / "msg.txt"
        compose_commit.commit_main_no_exit(["--status-file", str(sf), "--output", str(out)])
        assert out.exists()
        assert "test: add" in out.read_text(encoding="utf-8")

    def test_missing_status_file(self, compose_commit, tmp_path, capsys):
        rc = compose_commit.commit_main_no_exit(["--status-file", str(tmp_path / "nope.json")])
        assert rc == 2
        assert "not found" in capsys.readouterr().out

    def test_invalid_json(self, compose_commit, tmp_path, capsys):
        sf = tmp_path / "status.json"
        sf.write_text("{broken", encoding="utf-8")
        rc = compose_commit.commit_main_no_exit(["--status-file", str(sf)])
        assert rc == 2
        assert "invalid" in capsys.readouterr().out
